---
- name: Install nginx and verify
  hosts: ansible-testing
  collections:
    - oracle.oci
    
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest

    - name: start nginx
      service:
          name: nginx
          state: started

    - name: "Check if NGINX is installed"
      package_facts:
        manager: auto

    - name: "NGINX test result"
      debug: 
        msg: "NGINX found"
      when: "'nginx' in ansible_facts.packages"

    - name: "NGINX test result"
      debug: 
        msg: "NGINX NOT found"
      when: "'nginx' not in ansible_facts.packages"
